# Generated by Django 5.2 on 2026-02-20 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_subcategory_product_price_must_be_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='inventory.subcategory'),
        ),
    ]
