# Generated by Django 5.2 on 2026-03-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_user_product_user_subcategory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
