# Generated by Django 5.2 on 2026-05-21 03:33

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_description_product_image_patternfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternfile',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patternfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=inventory.models.product_pattern_path),
        ),
    ]
