# Generated by Django 5.2 on 2026-05-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_patternfile_url_alter_patternfile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
