# Generated by Django 5.2 on 2026-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='patternDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
